repos:
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
    -   id: gitlint
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        language_version: python3
        additional_dependencies:
        -   flake8-bugbear==19.8.0
        -   flake8-builtins==1.4.1
        -   flake8-comprehensions==3.1.4
        -   flake8-docstrings==1.5.0
        -   pep8-naming==0.9.1
        exclude: ^tests/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.750
    hooks:
    -   id: mypy
        language_version: python3
        exclude: ^tests/
