name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  lint:
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install gitlint
      - run: gitlint
      - uses: pre-commit/action@v2.0.0
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        python: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: python formset.py
