name: CI

on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        python: [3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Set PY
        run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pip install gitlint
      - run: gitlint
      - uses: pre-commit/action@v1.0.0
  test:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        python: [2.7, 3.5, 3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - run: python formset.py
